# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
   imageName: 'investigo'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: $(imageName)
   command: build
   Dockerfile: application-code/InvestiGO/Dockerfile
- task: AzureWebAppContainer@1
  inputs:
   azureSubscription: 'Azure subscription 1(c17d4207-e763-47a0-a5e8-13c3c8a4fafb)'
   appName: 'investigo'
   containers: 'investigo'